### ISSUE TITLE
rbamtools is orphaned so cannot install on R 3.6.1

### ISSUE THREAD

**Issue by 690645258** [Vivianstats/AIDE#3]
Trying to install AIDE on R version 3.6.1 but rbamtools is orphaned and not compatible with that version of R so AIDE is failing to install.

http://bioconductor.org/packages/release/bioc/html/Rsamtools.html looks like a maintained alternative that may work instead?

**Comment by wendelljpereira** [comment]
I am experiencing the same problem. I also tried to install it in the versions 3.5 and 3.4.3 and got the same error. Could you please inform it what version of R did you test your software? 

Would be great if you can substitute this package for one compatible, as suggested above.

**Comment by Vivianstats** [comment]
Hello! I'm sorry that I didn't get notification emails from the system and I just saw your comments last week.

I have fixed the issue and replaced rbamtools with Rsamtools.

Thank you both for reporting the issue!

**Comment by 690645258** [comment]
Can confirm it installs now, thanks very much!
